# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c63e8a4983575676f365e60b900cb2b5cacd97201f354131e18e249b490fcb5459543a34b640564359b1949d119378a3b08e5ade1abddd4054f940ff25a4819a

test:
  secret_key_base: 6fe93128988a29d30677e5312d43bd3589d2ba351b40113bfec9169ebdf22261e3641f28240706513694bbff1ada46ed303a7d7cad9a2d4e68c988140ebe4094

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
